# Generated by Django 4.1.6 on 2023-03-06 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.FileField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(default=None, max_length=100, null=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_baixa', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='material_carga.setor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_bmp', models.IntegerField(unique=True)),
                ('nomenclatura', models.CharField(max_length=1000)),
                ('n_serie', models.CharField(max_length=100)),
                ('vl_atualizado', models.FloatField()),
                ('vl_liquido', models.FloatField()),
                ('situacao', models.CharField(default=None, max_length=50)),
                ('imagem', models.FileField(blank=True, default='', upload_to='')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='material_carga.conta')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='material_carga.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('cautela', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='material_carga.cautela')),
                ('material', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='material_carga.material')),
            ],
        ),
        migrations.AddField(
            model_name='cautela',
            name='Perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='material_carga.perfil'),
        ),
    ]
