# Generated by Django 4.1.6 on 2023-10-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_carga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
